on:
  push:
    branches: [main]

env:
  python_version: '3.10'

name: CI

jobs:

  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ env.python_version }}
      - name: Use Python Dependency Cache
        uses: actions/cache@v3.0.9
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: python -m pip install poetry==1.2.1
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install Python Dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest
